### ISSUE TITLE
serving runtime contract - cgroups v2 support

### ISSUE THREAD

**Issue by dprotaso** [knative/specs#105]
cgroup v2 support in K8s went stable with v1.25. Generally it's replacing cgroups v1.

Currently the Knative runtime spec [mentions](https://github.com/knative/specs/blob/main/specs/serving/runtime-contract.md#control-groups) mentions operators _MAY_ adjust resource limits and _SHOULD_ expose those limits via cgroup v1 fs files.

> The serverless platform MAY automatically adjust the resource limits (e.g. CPU) based on observed resource usage. The limits enforced to a container [SHOULD](https://github.com/knative/serving/blob/main/test/conformance/runtime/cgroup_test.go) be exposed in
> 
>     /sys/fs/cgroup/memory/memory.limit_in_bytes
>     /sys/fs/cgroup/cpu/cpu.cfs_period_us
>     /sys/fs/cgroup/cpu/cpu.cfs_quota_us

To support v2 we need to list out alternative files to read limits from and probably specify it's a operator choice.

**Comment by evankanderson** [comment]
Ooh, good callout! Thanks!

When the runtime spec was written, `cgroups v2` was just starting (October 2015, apparently).

**Comment by evankanderson** [comment]
Doc ref: https://docs.kernel.org/admin-guide/cgroup-v2.html

**Comment by dprotaso** [comment]
Serving conformance tests also fails on these cgroups v2 environments - https://github.com/knative/serving/issues/13529
