### ISSUE TITLE
[Eventing - Control Plane] Event Delivery Test Plan

### ISSUE THREAD

**Issue by nainaz** [knative/specs#49]
### Description
---

This issue describes the creation of a "Manual Testing Plan" for a portion of the Eventing Spec.

Below is a link to the Spec Sub-heading which this issue is referencing, alongside a template upon which you should base your PR.

**Link to Spec**: https://github.com/knative/specs/blob/main/specs/eventing/control-plane.md#event-delivery

**Template**: https://hackmd.io/D1S9NPaRTG2dcyFtdURSww?view

If you have any questions, please reach out in the #conformance channel on Slack

---

### Acceptance Criteria
---
- [ ] Contributing to the right place

GIVEN I am accepting the PR that closes this issue 
WHEN I inspect the .md file 
THEN I see it is being committed to the /test/test-plan/ folder in the specs repo

- [ ]   Conformance to Template

GIVEN I am reviewing the submitted .md file 
WHEN I compare it to the template linked above 
THEN I see that the submitted .md conforms to the template 

- [ ]  Coverage of Spec

GIVEN I am reviewing the submitted .md file
WHEN I compare the .md file to the Event Delivery subheading in the spec
THEN all of the  "MUST" "MUST NOT" and "REQUIRED" sentences under the Event Delivery sub-heading are covered within the submitted .md file 

- [ ] Coverage of Tests

GIVEN I am running each of the tests in the submitted .md file 
AND each test has a expected output
WHEN I am finished running the tests 
THEN all of my tests pass (when compared to the expected output)
AND at least 2 reviewers feel it is properly covering all portions of the spec outlined at the top .md file

**Comment by odacremolbap** [comment]
Can I get assigned this one, please?
